"""add image_path to stylists

Revision ID: 1babeebc1dd0
Revises: 409679fac50e
Create Date: 2026-05-03 21:01:19.229399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1babeebc1dd0'
down_revision = '409679fac50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
