"""initial

Revision ID: 409679fac50e
Revises: 
Create Date: 2026-04-25 12:50:43.671816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409679fac50e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('first_visit_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('menus',
    sa.Column('menu_id', sa.String(length=5), nullable=False),
    sa.Column('menu_name', sa.String(length=30), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_table('ranks',
    sa.Column('rank_id', sa.String(length=1), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('rank_id')
    )
    op.create_table('menu_prices',
    sa.Column('menu_id', sa.String(length=5), nullable=False),
    sa.Column('rank_id', sa.String(length=1), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.CheckConstraint('price > 0', name='check_price_positive'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.rank_id'], ),
    sa.PrimaryKeyConstraint('menu_id', 'rank_id')
    )
    op.create_table('stylists',
    sa.Column('stylist_id', sa.String(length=10), nullable=False),
    sa.Column('stylist_name', sa.String(length=30), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('rank_id', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.rank_id'], ),
    sa.PrimaryKeyConstraint('stylist_id')
    )
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('stylist_id', sa.String(length=10), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['stylist_id'], ['stylists.stylist_id'], ),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('stylist_id', 'reservation_date', 'start_time', name='unique_reservation')
    )
    op.create_table('reservation_menus',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ),
    sa.PrimaryKeyConstraint('reservation_id', 'menu_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_menus')
    op.drop_table('reservations')
    op.drop_table('stylists')
    op.drop_table('menu_prices')
    op.drop_table('ranks')
    op.drop_table('menus')
    op.drop_table('customers')
    # ### end Alembic commands ###
